name: oggm_env
channels:
  - conda-forge
dependencies:
  - jupyter
  - jupyterlab
  - numpy
  - scipy
  - pandas
  - shapely
  - matplotlib
  - Pillow
  - netcdf4
  - scikit-image
  - scikit-learn
  - configobj
  - xarray
  - pytest
  - dask
  - bottleneck
  - pyproj
  - cartopy
  - geopandas
  - rioxarray
  - seaborn
  - pytables
  - salem
  - motionless
  - seaborn
  - holoviews
  - geoviews
  - hvplot
  - pip
  - pip:
    - joblib
    - progressbar2
    - git+https://github.com/OGGM/oggm-edu
    - oggm
